#!/usr/bin/env perl

use strict;
use warnings;
use FindBin '$RealBin';

# This script initializes a Spacchetti project

print `cp $RealBin/templates/gitignore .gitignore`;
print `cp $RealBin/templates/spacchetti.dhall spacchetti.dhall`;
print `cp $RealBin/templates/packages.dhall packages.dhall`;
print `mkdir -p src`;
print `mkdir -p test`;
print `cp $RealBin/templates/srcMain.purs src/Main.purs`;
print `cp $RealBin/templates/testMain.purs test/Main.purs`;

print "initialized Spacchetti project.\n";
