#!/usr/bin/env perl

use strict;
use warnings;
use FindBin '$RealBin';
use feature 'say';

print `$RealBin/spacchetti-make-json keep`;

my $json_path = '.spacchetti/spacchetti.json';

my @direct_deps = `jq '.dependencies | values[]' $json_path`;

my %visited = ();

sub getDeps {
    my ($name) = @_;
    chomp($name);

    if ($visited{$name}) {
        return;
    }

    $visited{$name} = 1;

    my @reverse_deps = `jq '.packages.${name}.dependencies | values[]' $json_path`;

    foreach my $target (@reverse_deps) {
        getDeps($target);
    }
}

foreach my $target (@direct_deps) {
    getDeps($target);
}

say for keys %visited;
