#!/usr/bin/env perl

use strict;
use warnings;
use FindBin '$RealBin';
use feature 'say';

print `$RealBin/spacchetti-make-json keep`;

my $json_path = '.spacchetti/spacchetti.json';

my @deps = `$RealBin/spacchetti-get-deps`;

my @globs = ();

sub makeGlob {
    my ($name) = @_;
    chomp($name);
    $name =~ s/"//g;

    my $version = `jq '.packages.$name.version' $json_path -r`;
    chomp($version);

    my $glob = "\".spacchetti/${name}/${version}/src/**/*.purs\"";

    push @globs, $glob;
}

foreach my $target (@deps) {
    makeGlob($target);
}

say for @globs;
