#!/usr/bin/env perl

use strict;
use warnings;
use FindBin '$RealBin';
use feature 'say';

print `$RealBin/spacchetti-make-json`;

my $json_path = '.spacchetti/spacchetti.json';

my @deps = `$RealBin/spacchetti-get-deps`;

my $num = $#deps + 1;

say "Installing $num packages";

my @pids;

foreach my $target (@deps) {
    chomp($target);

    my $pid = fork;

    if (not defined $pid) {
        die "Couldn't fork new child processes\n";
    } elsif ($pid == 0) {
        print `$RealBin/spacchetti-install-package $target`;

        if ($? != 0) {
            die "Installation failed at $target";
        } else {
            exit;
        }
    } else {
        push @pids, $pid;
    }
}

for my $pid (@pids) {
    waitpid $pid, 0;
}

say "Installed $num packages."
